version: '3.2'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  algolia-webhook:
    image: eyuelberga/peernotes-algolia-webhook:latest
    ports:
      - '3001:3000'
    environment:
      ALGOLIA_ADMIN_API_KEY: ${ALGOLIA_ADMIN_API_KEY}
      ALGOLIA_APP_ID: ${ALGOLIA_APP_ID}
      ALGOLIA_INDEX: ${ALGOLIA_INDEX}
      HASURA_GRAPHQL_URL: 'http://graphql-engine:8080/v1/graphql'
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}

  graphql-engine:
    image: hasura/graphql-engine:v2.0.10.cli-migrations-v3
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
      - 'algolia-webhook'
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${HASURA_GRAPHQL_METADATA_DATABASE_URL}
      PG_DATABASE_URL: ${HASURA_GRAPHQL_METADATA_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      ALGOLIA_WEBHOOK_URL: 'http://172.17.0.1:3001/'
  web:
    image: eyuelberga/peernotes-web-test:latest
    ports:
      - '3000:80'
    depends_on:
      - 'graphql-engine'
    restart: always
    environment:
      REACT_APP_GRAPHQL_HTTPS_URL: 'http://localhost:8080/v1/graphql'
      REACT_APP_GRAPHQL_WSS_URL: 'ws://localhost:8080/v1/graphql'
      REACT_APP_AUTH0_DOMAIN: ${REACT_APP_AUTH0_DOMAIN}
      REACT_APP_AUTH0_CLIENT_ID: ${REACT_APP_AUTH0_CLIENT_ID}
      REACT_APP_AUTH0_AUDIENCE: ${REACT_APP_AUTH0_AUDIENCE}
      REACT_APP_CLOUDNARY_CLOUD_NAME: ${REACT_APP_CLOUDNARY_CLOUD_NAME}
      REACT_APP_CLOUDNARY_UPLOAD_PRESET: ${REACT_APP_CLOUDNARY_UPLOAD_PRESET}
      REACT_APP_ALGOLIA_APP_ID: ${REACT_APP_ALGOLIA_APP_ID}
      REACT_APP_ALGOLIA_API_KEY: ${REACT_APP_ALGOLIA_API_KEY}
      REACT_APP_ALGOLIA_INDEX: ${REACT_APP_ALGOLIA_INDEX}
volumes:
  db_data:
