name: Publish Docker Images
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker images
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          docker build web --file web/Dockerfile --tag eyuelberga/peernotes-web:$RELEASE_VERSION
          docker build web --file web/Dockerfile --build-arg "ENV=TEST" --tag eyuelberga/peernotes-web-test:$RELEASE_VERSION
          docker build algolia-webhook --file algolia-webhook/Dockerfile --tag eyuelberga/peernotes-algolia-webhook:$RELEASE_VERSION
      - name: Push to docker hub
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          docker push eyuelberga/peernotes-web:$RELEASE_VERSION
          docker push eyuelberga/peernotes-web-test:$RELEASE_VERSION
          docker push eyuelberga/peernotes-algolia-webhook:$RELEASE_VERSION
